# spring.application.name=api-gateway
# server.port=8765

# spring.cloud.gateway.globalcors.cors-configurations.'[/**]'.allowedOrigins:
# spring.cloud.gateway.discovery.locator.enabled=true
# spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# eureka.instance.hostname=localhost
# eureka.client.fetch-registry=false
# eureka.client.register-with-eureka=false

server:
    port: 8765

eureka:
    client:
        service-url:
            default-zone: "http://localhost:8761"
jwt:
    secret: supersecret

authentication:
    enabled: true

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: userdetails
                  predicates:
                    - Path=/userdetails/
                  uri: "http://localhost:8080"
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedHeaders: "*"
                        allowedMethods:
                        - GET
                        - POST