version: '4'

services:
  postgres:
    image: postgres:latest
    container_name: userdetails
    environment:
      POSTGRES_SQL_USERNAME: postgres
      POSTGRES_PASSWORD: demo1234
    volumes:
       - ./postgres:/var/lib/postgres
    ports:
      - 5432:5432

